// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgID.proto

package DotaMsgID;

public final class MsgID {
  private MsgID() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code DotaMsgID.MSGID}
   */
  public enum MSGID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CSID_C2L_LOGINSERVER = 101;</code>
     *
     * <pre>
     *请求登陆
     * </pre>
     */
    CSID_C2L_LOGINSERVER(0, 101),
    /**
     * <code>CSID_L2C_LOGINSERVER = 102;</code>
     *
     * <pre>
     *返回登陆结果  
     * </pre>
     */
    CSID_L2C_LOGINSERVER(1, 102),
    /**
     * <code>CSID_C2S_PUB_BEAT = 30100;</code>
     *
     * <pre>
     *心跳请求
     * </pre>
     */
    CSID_C2S_PUB_BEAT(2, 30100),
    /**
     * <code>CSID_S2C_PUB_BEAT = 30101;</code>
     *
     * <pre>
     *心跳应答
     * </pre>
     */
    CSID_S2C_PUB_BEAT(3, 30101),
    ;

    /**
     * <code>CSID_C2L_LOGINSERVER = 101;</code>
     *
     * <pre>
     *请求登陆
     * </pre>
     */
    public static final int CSID_C2L_LOGINSERVER_VALUE = 101;
    /**
     * <code>CSID_L2C_LOGINSERVER = 102;</code>
     *
     * <pre>
     *返回登陆结果  
     * </pre>
     */
    public static final int CSID_L2C_LOGINSERVER_VALUE = 102;
    /**
     * <code>CSID_C2S_PUB_BEAT = 30100;</code>
     *
     * <pre>
     *心跳请求
     * </pre>
     */
    public static final int CSID_C2S_PUB_BEAT_VALUE = 30100;
    /**
     * <code>CSID_S2C_PUB_BEAT = 30101;</code>
     *
     * <pre>
     *心跳应答
     * </pre>
     */
    public static final int CSID_S2C_PUB_BEAT_VALUE = 30101;


    public final int getNumber() { return value; }

    public static MSGID valueOf(int value) {
      switch (value) {
        case 101: return CSID_C2L_LOGINSERVER;
        case 102: return CSID_L2C_LOGINSERVER;
        case 30100: return CSID_C2S_PUB_BEAT;
        case 30101: return CSID_S2C_PUB_BEAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MSGID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MSGID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MSGID>() {
            public MSGID findValueByNumber(int number) {
              return MSGID.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DotaMsgID.MsgID.getDescriptor().getEnumTypes().get(0);
    }

    private static final MSGID[] VALUES = values();

    public static MSGID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MSGID(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DotaMsgID.MSGID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013MsgID.proto\022\tDotaMsgID*m\n\005MSGID\022\030\n\024CSI" +
      "D_C2L_LOGINSERVER\020e\022\030\n\024CSID_L2C_LOGINSER" +
      "VER\020f\022\027\n\021CSID_C2S_PUB_BEAT\020\224\353\001\022\027\n\021CSID_S" +
      "2C_PUB_BEAT\020\225\353\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
