// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgData.proto

package DotaMsgData;

public final class MsgData {
  private MsgData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MSG_C2L_LOGINSERVEROrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string account = 1;
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    boolean hasAccount();
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    java.lang.String getAccount();
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    // required string password = 2;
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // required string key = 3;
    /**
     * <code>required string key = 3;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>required string key = 3;</code>
     *
     * <pre>
     * </pre>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 3;</code>
     *
     * <pre>
     * </pre>
     */
    com.google.protobuf.ByteString
        getKeyBytes();
  }
  /**
   * Protobuf type {@code DotaMsgData.MSG_C2L_LOGINSERVER}
   */
  public static final class MSG_C2L_LOGINSERVER extends
      com.google.protobuf.GeneratedMessage
      implements MSG_C2L_LOGINSERVEROrBuilder {
    // Use MSG_C2L_LOGINSERVER.newBuilder() to construct.
    private MSG_C2L_LOGINSERVER(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MSG_C2L_LOGINSERVER(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MSG_C2L_LOGINSERVER defaultInstance;
    public static MSG_C2L_LOGINSERVER getDefaultInstance() {
      return defaultInstance;
    }

    public MSG_C2L_LOGINSERVER getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_C2L_LOGINSERVER(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              account_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              key_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DotaMsgData.MsgData.MSG_C2L_LOGINSERVER.class, DotaMsgData.MsgData.MSG_C2L_LOGINSERVER.Builder.class);
    }

    public static com.google.protobuf.Parser<MSG_C2L_LOGINSERVER> PARSER =
        new com.google.protobuf.AbstractParser<MSG_C2L_LOGINSERVER>() {
      public MSG_C2L_LOGINSERVER parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_C2L_LOGINSERVER(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MSG_C2L_LOGINSERVER> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private java.lang.Object account_;
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string key = 3;
    public static final int KEY_FIELD_NUMBER = 3;
    private java.lang.Object key_;
    /**
     * <code>required string key = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string key = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      account_ = "";
      password_ = "";
      key_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DotaMsgData.MsgData.MSG_C2L_LOGINSERVER prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DotaMsgData.MSG_C2L_LOGINSERVER}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DotaMsgData.MsgData.MSG_C2L_LOGINSERVEROrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DotaMsgData.MsgData.MSG_C2L_LOGINSERVER.class, DotaMsgData.MsgData.MSG_C2L_LOGINSERVER.Builder.class);
      }

      // Construct using DotaMsgData.MsgData.MSG_C2L_LOGINSERVER.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_descriptor;
      }

      public DotaMsgData.MsgData.MSG_C2L_LOGINSERVER getDefaultInstanceForType() {
        return DotaMsgData.MsgData.MSG_C2L_LOGINSERVER.getDefaultInstance();
      }

      public DotaMsgData.MsgData.MSG_C2L_LOGINSERVER build() {
        DotaMsgData.MsgData.MSG_C2L_LOGINSERVER result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DotaMsgData.MsgData.MSG_C2L_LOGINSERVER buildPartial() {
        DotaMsgData.MsgData.MSG_C2L_LOGINSERVER result = new DotaMsgData.MsgData.MSG_C2L_LOGINSERVER(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.key_ = key_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DotaMsgData.MsgData.MSG_C2L_LOGINSERVER) {
          return mergeFrom((DotaMsgData.MsgData.MSG_C2L_LOGINSERVER)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DotaMsgData.MsgData.MSG_C2L_LOGINSERVER other) {
        if (other == DotaMsgData.MsgData.MSG_C2L_LOGINSERVER.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          bitField0_ |= 0x00000001;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000004;
          key_ = other.key_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DotaMsgData.MsgData.MSG_C2L_LOGINSERVER parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DotaMsgData.MsgData.MSG_C2L_LOGINSERVER) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string account = 1;
      private java.lang.Object account_ = "";
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }

      // required string password = 2;
      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // required string key = 3;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string key = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DotaMsgData.MSG_C2L_LOGINSERVER)
    }

    static {
      defaultInstance = new MSG_C2L_LOGINSERVER(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DotaMsgData.MSG_C2L_LOGINSERVER)
  }

  public interface MSG_L2C_LOGINSERVEROrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 ret = 1;
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *0≥…π¶£¨∑Ò‘ÚŒ™¥ÌŒÛ∫≈
     * </pre>
     */
    boolean hasRet();
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *0≥…π¶£¨∑Ò‘ÚŒ™¥ÌŒÛ∫≈
     * </pre>
     */
    int getRet();
  }
  /**
   * Protobuf type {@code DotaMsgData.MSG_L2C_LOGINSERVER}
   */
  public static final class MSG_L2C_LOGINSERVER extends
      com.google.protobuf.GeneratedMessage
      implements MSG_L2C_LOGINSERVEROrBuilder {
    // Use MSG_L2C_LOGINSERVER.newBuilder() to construct.
    private MSG_L2C_LOGINSERVER(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MSG_L2C_LOGINSERVER(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MSG_L2C_LOGINSERVER defaultInstance;
    public static MSG_L2C_LOGINSERVER getDefaultInstance() {
      return defaultInstance;
    }

    public MSG_L2C_LOGINSERVER getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_L2C_LOGINSERVER(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DotaMsgData.MsgData.MSG_L2C_LOGINSERVER.class, DotaMsgData.MsgData.MSG_L2C_LOGINSERVER.Builder.class);
    }

    public static com.google.protobuf.Parser<MSG_L2C_LOGINSERVER> PARSER =
        new com.google.protobuf.AbstractParser<MSG_L2C_LOGINSERVER>() {
      public MSG_L2C_LOGINSERVER parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_L2C_LOGINSERVER(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MSG_L2C_LOGINSERVER> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 ret = 1;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *0≥…π¶£¨∑Ò‘ÚŒ™¥ÌŒÛ∫≈
     * </pre>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *0≥…π¶£¨∑Ò‘ÚŒ™¥ÌŒÛ∫≈
     * </pre>
     */
    public int getRet() {
      return ret_;
    }

    private void initFields() {
      ret_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ret_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ret_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DotaMsgData.MsgData.MSG_L2C_LOGINSERVER prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DotaMsgData.MSG_L2C_LOGINSERVER}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DotaMsgData.MsgData.MSG_L2C_LOGINSERVEROrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DotaMsgData.MsgData.MSG_L2C_LOGINSERVER.class, DotaMsgData.MsgData.MSG_L2C_LOGINSERVER.Builder.class);
      }

      // Construct using DotaMsgData.MsgData.MSG_L2C_LOGINSERVER.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_descriptor;
      }

      public DotaMsgData.MsgData.MSG_L2C_LOGINSERVER getDefaultInstanceForType() {
        return DotaMsgData.MsgData.MSG_L2C_LOGINSERVER.getDefaultInstance();
      }

      public DotaMsgData.MsgData.MSG_L2C_LOGINSERVER build() {
        DotaMsgData.MsgData.MSG_L2C_LOGINSERVER result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DotaMsgData.MsgData.MSG_L2C_LOGINSERVER buildPartial() {
        DotaMsgData.MsgData.MSG_L2C_LOGINSERVER result = new DotaMsgData.MsgData.MSG_L2C_LOGINSERVER(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DotaMsgData.MsgData.MSG_L2C_LOGINSERVER) {
          return mergeFrom((DotaMsgData.MsgData.MSG_L2C_LOGINSERVER)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DotaMsgData.MsgData.MSG_L2C_LOGINSERVER other) {
        if (other == DotaMsgData.MsgData.MSG_L2C_LOGINSERVER.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRet()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DotaMsgData.MsgData.MSG_L2C_LOGINSERVER parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DotaMsgData.MsgData.MSG_L2C_LOGINSERVER) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 ret = 1;
      private int ret_ ;
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *0≥…π¶£¨∑Ò‘ÚŒ™¥ÌŒÛ∫≈
       * </pre>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *0≥…π¶£¨∑Ò‘ÚŒ™¥ÌŒÛ∫≈
       * </pre>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *0≥…π¶£¨∑Ò‘ÚŒ™¥ÌŒÛ∫≈
       * </pre>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *0≥…π¶£¨∑Ò‘ÚŒ™¥ÌŒÛ∫≈
       * </pre>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DotaMsgData.MSG_L2C_LOGINSERVER)
    }

    static {
      defaultInstance = new MSG_L2C_LOGINSERVER(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DotaMsgData.MSG_L2C_LOGINSERVER)
  }

  public interface MSG_C2S_PUB_BEATOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code DotaMsgData.MSG_C2S_PUB_BEAT}
   */
  public static final class MSG_C2S_PUB_BEAT extends
      com.google.protobuf.GeneratedMessage
      implements MSG_C2S_PUB_BEATOrBuilder {
    // Use MSG_C2S_PUB_BEAT.newBuilder() to construct.
    private MSG_C2S_PUB_BEAT(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MSG_C2S_PUB_BEAT(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MSG_C2S_PUB_BEAT defaultInstance;
    public static MSG_C2S_PUB_BEAT getDefaultInstance() {
      return defaultInstance;
    }

    public MSG_C2S_PUB_BEAT getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_C2S_PUB_BEAT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DotaMsgData.MsgData.MSG_C2S_PUB_BEAT.class, DotaMsgData.MsgData.MSG_C2S_PUB_BEAT.Builder.class);
    }

    public static com.google.protobuf.Parser<MSG_C2S_PUB_BEAT> PARSER =
        new com.google.protobuf.AbstractParser<MSG_C2S_PUB_BEAT>() {
      public MSG_C2S_PUB_BEAT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_C2S_PUB_BEAT(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MSG_C2S_PUB_BEAT> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DotaMsgData.MsgData.MSG_C2S_PUB_BEAT prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DotaMsgData.MSG_C2S_PUB_BEAT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DotaMsgData.MsgData.MSG_C2S_PUB_BEATOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DotaMsgData.MsgData.MSG_C2S_PUB_BEAT.class, DotaMsgData.MsgData.MSG_C2S_PUB_BEAT.Builder.class);
      }

      // Construct using DotaMsgData.MsgData.MSG_C2S_PUB_BEAT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_descriptor;
      }

      public DotaMsgData.MsgData.MSG_C2S_PUB_BEAT getDefaultInstanceForType() {
        return DotaMsgData.MsgData.MSG_C2S_PUB_BEAT.getDefaultInstance();
      }

      public DotaMsgData.MsgData.MSG_C2S_PUB_BEAT build() {
        DotaMsgData.MsgData.MSG_C2S_PUB_BEAT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DotaMsgData.MsgData.MSG_C2S_PUB_BEAT buildPartial() {
        DotaMsgData.MsgData.MSG_C2S_PUB_BEAT result = new DotaMsgData.MsgData.MSG_C2S_PUB_BEAT(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DotaMsgData.MsgData.MSG_C2S_PUB_BEAT) {
          return mergeFrom((DotaMsgData.MsgData.MSG_C2S_PUB_BEAT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DotaMsgData.MsgData.MSG_C2S_PUB_BEAT other) {
        if (other == DotaMsgData.MsgData.MSG_C2S_PUB_BEAT.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DotaMsgData.MsgData.MSG_C2S_PUB_BEAT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DotaMsgData.MsgData.MSG_C2S_PUB_BEAT) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DotaMsgData.MSG_C2S_PUB_BEAT)
    }

    static {
      defaultInstance = new MSG_C2S_PUB_BEAT(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DotaMsgData.MSG_C2S_PUB_BEAT)
  }

  public interface MSG_S2C_PUB_BEATOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code DotaMsgData.MSG_S2C_PUB_BEAT}
   */
  public static final class MSG_S2C_PUB_BEAT extends
      com.google.protobuf.GeneratedMessage
      implements MSG_S2C_PUB_BEATOrBuilder {
    // Use MSG_S2C_PUB_BEAT.newBuilder() to construct.
    private MSG_S2C_PUB_BEAT(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MSG_S2C_PUB_BEAT(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MSG_S2C_PUB_BEAT defaultInstance;
    public static MSG_S2C_PUB_BEAT getDefaultInstance() {
      return defaultInstance;
    }

    public MSG_S2C_PUB_BEAT getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_S2C_PUB_BEAT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DotaMsgData.MsgData.MSG_S2C_PUB_BEAT.class, DotaMsgData.MsgData.MSG_S2C_PUB_BEAT.Builder.class);
    }

    public static com.google.protobuf.Parser<MSG_S2C_PUB_BEAT> PARSER =
        new com.google.protobuf.AbstractParser<MSG_S2C_PUB_BEAT>() {
      public MSG_S2C_PUB_BEAT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_S2C_PUB_BEAT(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MSG_S2C_PUB_BEAT> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DotaMsgData.MsgData.MSG_S2C_PUB_BEAT prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DotaMsgData.MSG_S2C_PUB_BEAT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DotaMsgData.MsgData.MSG_S2C_PUB_BEATOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DotaMsgData.MsgData.MSG_S2C_PUB_BEAT.class, DotaMsgData.MsgData.MSG_S2C_PUB_BEAT.Builder.class);
      }

      // Construct using DotaMsgData.MsgData.MSG_S2C_PUB_BEAT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DotaMsgData.MsgData.internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_descriptor;
      }

      public DotaMsgData.MsgData.MSG_S2C_PUB_BEAT getDefaultInstanceForType() {
        return DotaMsgData.MsgData.MSG_S2C_PUB_BEAT.getDefaultInstance();
      }

      public DotaMsgData.MsgData.MSG_S2C_PUB_BEAT build() {
        DotaMsgData.MsgData.MSG_S2C_PUB_BEAT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DotaMsgData.MsgData.MSG_S2C_PUB_BEAT buildPartial() {
        DotaMsgData.MsgData.MSG_S2C_PUB_BEAT result = new DotaMsgData.MsgData.MSG_S2C_PUB_BEAT(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DotaMsgData.MsgData.MSG_S2C_PUB_BEAT) {
          return mergeFrom((DotaMsgData.MsgData.MSG_S2C_PUB_BEAT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DotaMsgData.MsgData.MSG_S2C_PUB_BEAT other) {
        if (other == DotaMsgData.MsgData.MSG_S2C_PUB_BEAT.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DotaMsgData.MsgData.MSG_S2C_PUB_BEAT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DotaMsgData.MsgData.MSG_S2C_PUB_BEAT) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DotaMsgData.MSG_S2C_PUB_BEAT)
    }

    static {
      defaultInstance = new MSG_S2C_PUB_BEAT(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DotaMsgData.MSG_S2C_PUB_BEAT)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgData.proto\022\013DotaMsgData\"E\n\023MSG_C2L_" +
      "LOGINSERVER\022\017\n\007account\030\001 \002(\t\022\020\n\010password" +
      "\030\002 \002(\t\022\013\n\003key\030\003 \002(\t\"\"\n\023MSG_L2C_LOGINSERV" +
      "ER\022\013\n\003ret\030\001 \002(\005\"\022\n\020MSG_C2S_PUB_BEAT\"\022\n\020M" +
      "SG_S2C_PUB_BEAT"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DotaMsgData_MSG_C2L_LOGINSERVER_descriptor,
              new java.lang.String[] { "Account", "Password", "Key", });
          internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DotaMsgData_MSG_L2C_LOGINSERVER_descriptor,
              new java.lang.String[] { "Ret", });
          internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DotaMsgData_MSG_C2S_PUB_BEAT_descriptor,
              new java.lang.String[] { });
          internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DotaMsgData_MSG_S2C_PUB_BEAT_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
