// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace DotaMsgData {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public static partial class MsgData {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_DotaMsgData_MSG_C2L_LOGINSERVER__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::DotaMsgData.MSG_C2L_LOGINSERVER, global::DotaMsgData.MSG_C2L_LOGINSERVER.Builder> internal__static_DotaMsgData_MSG_C2L_LOGINSERVER__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_DotaMsgData_MSG_L2C_LOGINSERVER__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::DotaMsgData.MSG_L2C_LOGINSERVER, global::DotaMsgData.MSG_L2C_LOGINSERVER.Builder> internal__static_DotaMsgData_MSG_L2C_LOGINSERVER__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_DotaMsgData_MSG_C2S_PUB_BEAT__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::DotaMsgData.MSG_C2S_PUB_BEAT, global::DotaMsgData.MSG_C2S_PUB_BEAT.Builder> internal__static_DotaMsgData_MSG_C2S_PUB_BEAT__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_DotaMsgData_MSG_S2C_PUB_BEAT__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::DotaMsgData.MSG_S2C_PUB_BEAT, global::DotaMsgData.MSG_S2C_PUB_BEAT.Builder> internal__static_DotaMsgData_MSG_S2C_PUB_BEAT__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static MsgData() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "Cg1Nc2dEYXRhLnByb3RvEgtEb3RhTXNnRGF0YSJFChNNU0dfQzJMX0xPR0lO" + 
          "U0VSVkVSEg8KB2FjY291bnQYASACKAkSEAoIcGFzc3dvcmQYAiACKAkSCwoD" + 
          "a2V5GAMgAigJIiIKE01TR19MMkNfTE9HSU5TRVJWRVISCwoDcmV0GAEgAigF" + 
          "IhIKEE1TR19DMlNfUFVCX0JFQVQiEgoQTVNHX1MyQ19QVUJfQkVBVA==");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_DotaMsgData_MSG_C2L_LOGINSERVER__Descriptor = Descriptor.MessageTypes[0];
        internal__static_DotaMsgData_MSG_C2L_LOGINSERVER__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::DotaMsgData.MSG_C2L_LOGINSERVER, global::DotaMsgData.MSG_C2L_LOGINSERVER.Builder>(internal__static_DotaMsgData_MSG_C2L_LOGINSERVER__Descriptor,
                new string[] { "Account", "Password", "Key", });
        internal__static_DotaMsgData_MSG_L2C_LOGINSERVER__Descriptor = Descriptor.MessageTypes[1];
        internal__static_DotaMsgData_MSG_L2C_LOGINSERVER__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::DotaMsgData.MSG_L2C_LOGINSERVER, global::DotaMsgData.MSG_L2C_LOGINSERVER.Builder>(internal__static_DotaMsgData_MSG_L2C_LOGINSERVER__Descriptor,
                new string[] { "Ret", });
        internal__static_DotaMsgData_MSG_C2S_PUB_BEAT__Descriptor = Descriptor.MessageTypes[2];
        internal__static_DotaMsgData_MSG_C2S_PUB_BEAT__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::DotaMsgData.MSG_C2S_PUB_BEAT, global::DotaMsgData.MSG_C2S_PUB_BEAT.Builder>(internal__static_DotaMsgData_MSG_C2S_PUB_BEAT__Descriptor,
                new string[] { });
        internal__static_DotaMsgData_MSG_S2C_PUB_BEAT__Descriptor = Descriptor.MessageTypes[3];
        internal__static_DotaMsgData_MSG_S2C_PUB_BEAT__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::DotaMsgData.MSG_S2C_PUB_BEAT, global::DotaMsgData.MSG_S2C_PUB_BEAT.Builder>(internal__static_DotaMsgData_MSG_S2C_PUB_BEAT__Descriptor,
                new string[] { });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class MSG_C2L_LOGINSERVER : pb::GeneratedMessage<MSG_C2L_LOGINSERVER, MSG_C2L_LOGINSERVER.Builder> {
    private MSG_C2L_LOGINSERVER() { }
    private static readonly MSG_C2L_LOGINSERVER defaultInstance = new MSG_C2L_LOGINSERVER().MakeReadOnly();
    private static readonly string[] _mSGC2LLOGINSERVERFieldNames = new string[] { "account", "key", "password" };
    private static readonly uint[] _mSGC2LLOGINSERVERFieldTags = new uint[] { 10, 26, 18 };
    public static MSG_C2L_LOGINSERVER DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MSG_C2L_LOGINSERVER DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MSG_C2L_LOGINSERVER ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::DotaMsgData.MsgData.internal__static_DotaMsgData_MSG_C2L_LOGINSERVER__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<MSG_C2L_LOGINSERVER, MSG_C2L_LOGINSERVER.Builder> InternalFieldAccessors {
      get { return global::DotaMsgData.MsgData.internal__static_DotaMsgData_MSG_C2L_LOGINSERVER__FieldAccessorTable; }
    }
    
    public const int AccountFieldNumber = 1;
    private bool hasAccount;
    private string account_ = "";
    public bool HasAccount {
      get { return hasAccount; }
    }
    public string Account {
      get { return account_; }
    }
    
    public const int PasswordFieldNumber = 2;
    private bool hasPassword;
    private string password_ = "";
    public bool HasPassword {
      get { return hasPassword; }
    }
    public string Password {
      get { return password_; }
    }
    
    public const int KeyFieldNumber = 3;
    private bool hasKey;
    private string key_ = "";
    public bool HasKey {
      get { return hasKey; }
    }
    public string Key {
      get { return key_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasAccount) return false;
        if (!hasPassword) return false;
        if (!hasKey) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _mSGC2LLOGINSERVERFieldNames;
      if (hasAccount) {
        output.WriteString(1, field_names[0], Account);
      }
      if (hasPassword) {
        output.WriteString(2, field_names[2], Password);
      }
      if (hasKey) {
        output.WriteString(3, field_names[1], Key);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasAccount) {
          size += pb::CodedOutputStream.ComputeStringSize(1, Account);
        }
        if (hasPassword) {
          size += pb::CodedOutputStream.ComputeStringSize(2, Password);
        }
        if (hasKey) {
          size += pb::CodedOutputStream.ComputeStringSize(3, Key);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static MSG_C2L_LOGINSERVER ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MSG_C2L_LOGINSERVER ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MSG_C2L_LOGINSERVER ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MSG_C2L_LOGINSERVER ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MSG_C2L_LOGINSERVER ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MSG_C2L_LOGINSERVER ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MSG_C2L_LOGINSERVER ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MSG_C2L_LOGINSERVER ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MSG_C2L_LOGINSERVER ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MSG_C2L_LOGINSERVER ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MSG_C2L_LOGINSERVER MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MSG_C2L_LOGINSERVER prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<MSG_C2L_LOGINSERVER, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MSG_C2L_LOGINSERVER cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MSG_C2L_LOGINSERVER result;
      
      private MSG_C2L_LOGINSERVER PrepareBuilder() {
        if (resultIsReadOnly) {
          MSG_C2L_LOGINSERVER original = result;
          result = new MSG_C2L_LOGINSERVER();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MSG_C2L_LOGINSERVER MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::DotaMsgData.MSG_C2L_LOGINSERVER.Descriptor; }
      }
      
      public override MSG_C2L_LOGINSERVER DefaultInstanceForType {
        get { return global::DotaMsgData.MSG_C2L_LOGINSERVER.DefaultInstance; }
      }
      
      public override MSG_C2L_LOGINSERVER BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is MSG_C2L_LOGINSERVER) {
          return MergeFrom((MSG_C2L_LOGINSERVER) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MSG_C2L_LOGINSERVER other) {
        if (other == global::DotaMsgData.MSG_C2L_LOGINSERVER.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasAccount) {
          Account = other.Account;
        }
        if (other.HasPassword) {
          Password = other.Password;
        }
        if (other.HasKey) {
          Key = other.Key;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_mSGC2LLOGINSERVERFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _mSGC2LLOGINSERVERFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasAccount = input.ReadString(ref result.account_);
              break;
            }
            case 18: {
              result.hasPassword = input.ReadString(ref result.password_);
              break;
            }
            case 26: {
              result.hasKey = input.ReadString(ref result.key_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasAccount {
        get { return result.hasAccount; }
      }
      public string Account {
        get { return result.Account; }
        set { SetAccount(value); }
      }
      public Builder SetAccount(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasAccount = true;
        result.account_ = value;
        return this;
      }
      public Builder ClearAccount() {
        PrepareBuilder();
        result.hasAccount = false;
        result.account_ = "";
        return this;
      }
      
      public bool HasPassword {
        get { return result.hasPassword; }
      }
      public string Password {
        get { return result.Password; }
        set { SetPassword(value); }
      }
      public Builder SetPassword(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasPassword = true;
        result.password_ = value;
        return this;
      }
      public Builder ClearPassword() {
        PrepareBuilder();
        result.hasPassword = false;
        result.password_ = "";
        return this;
      }
      
      public bool HasKey {
        get { return result.hasKey; }
      }
      public string Key {
        get { return result.Key; }
        set { SetKey(value); }
      }
      public Builder SetKey(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder ClearKey() {
        PrepareBuilder();
        result.hasKey = false;
        result.key_ = "";
        return this;
      }
    }
    static MSG_C2L_LOGINSERVER() {
      object.ReferenceEquals(global::DotaMsgData.MsgData.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class MSG_L2C_LOGINSERVER : pb::GeneratedMessage<MSG_L2C_LOGINSERVER, MSG_L2C_LOGINSERVER.Builder> {
    private MSG_L2C_LOGINSERVER() { }
    private static readonly MSG_L2C_LOGINSERVER defaultInstance = new MSG_L2C_LOGINSERVER().MakeReadOnly();
    private static readonly string[] _mSGL2CLOGINSERVERFieldNames = new string[] { "ret" };
    private static readonly uint[] _mSGL2CLOGINSERVERFieldTags = new uint[] { 8 };
    public static MSG_L2C_LOGINSERVER DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MSG_L2C_LOGINSERVER DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MSG_L2C_LOGINSERVER ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::DotaMsgData.MsgData.internal__static_DotaMsgData_MSG_L2C_LOGINSERVER__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<MSG_L2C_LOGINSERVER, MSG_L2C_LOGINSERVER.Builder> InternalFieldAccessors {
      get { return global::DotaMsgData.MsgData.internal__static_DotaMsgData_MSG_L2C_LOGINSERVER__FieldAccessorTable; }
    }
    
    public const int RetFieldNumber = 1;
    private bool hasRet;
    private int ret_;
    public bool HasRet {
      get { return hasRet; }
    }
    public int Ret {
      get { return ret_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasRet) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _mSGL2CLOGINSERVERFieldNames;
      if (hasRet) {
        output.WriteInt32(1, field_names[0], Ret);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasRet) {
          size += pb::CodedOutputStream.ComputeInt32Size(1, Ret);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static MSG_L2C_LOGINSERVER ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MSG_L2C_LOGINSERVER ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MSG_L2C_LOGINSERVER ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MSG_L2C_LOGINSERVER ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MSG_L2C_LOGINSERVER ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MSG_L2C_LOGINSERVER ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MSG_L2C_LOGINSERVER ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MSG_L2C_LOGINSERVER ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MSG_L2C_LOGINSERVER ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MSG_L2C_LOGINSERVER ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MSG_L2C_LOGINSERVER MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MSG_L2C_LOGINSERVER prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<MSG_L2C_LOGINSERVER, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MSG_L2C_LOGINSERVER cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MSG_L2C_LOGINSERVER result;
      
      private MSG_L2C_LOGINSERVER PrepareBuilder() {
        if (resultIsReadOnly) {
          MSG_L2C_LOGINSERVER original = result;
          result = new MSG_L2C_LOGINSERVER();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MSG_L2C_LOGINSERVER MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::DotaMsgData.MSG_L2C_LOGINSERVER.Descriptor; }
      }
      
      public override MSG_L2C_LOGINSERVER DefaultInstanceForType {
        get { return global::DotaMsgData.MSG_L2C_LOGINSERVER.DefaultInstance; }
      }
      
      public override MSG_L2C_LOGINSERVER BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is MSG_L2C_LOGINSERVER) {
          return MergeFrom((MSG_L2C_LOGINSERVER) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MSG_L2C_LOGINSERVER other) {
        if (other == global::DotaMsgData.MSG_L2C_LOGINSERVER.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasRet) {
          Ret = other.Ret;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_mSGL2CLOGINSERVERFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _mSGL2CLOGINSERVERFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasRet = input.ReadInt32(ref result.ret_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasRet {
        get { return result.hasRet; }
      }
      public int Ret {
        get { return result.Ret; }
        set { SetRet(value); }
      }
      public Builder SetRet(int value) {
        PrepareBuilder();
        result.hasRet = true;
        result.ret_ = value;
        return this;
      }
      public Builder ClearRet() {
        PrepareBuilder();
        result.hasRet = false;
        result.ret_ = 0;
        return this;
      }
    }
    static MSG_L2C_LOGINSERVER() {
      object.ReferenceEquals(global::DotaMsgData.MsgData.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class MSG_C2S_PUB_BEAT : pb::GeneratedMessage<MSG_C2S_PUB_BEAT, MSG_C2S_PUB_BEAT.Builder> {
    private MSG_C2S_PUB_BEAT() { }
    private static readonly MSG_C2S_PUB_BEAT defaultInstance = new MSG_C2S_PUB_BEAT().MakeReadOnly();
    private static readonly string[] _mSGC2SPUBBEATFieldNames = new string[] {  };
    private static readonly uint[] _mSGC2SPUBBEATFieldTags = new uint[] {  };
    public static MSG_C2S_PUB_BEAT DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MSG_C2S_PUB_BEAT DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MSG_C2S_PUB_BEAT ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::DotaMsgData.MsgData.internal__static_DotaMsgData_MSG_C2S_PUB_BEAT__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<MSG_C2S_PUB_BEAT, MSG_C2S_PUB_BEAT.Builder> InternalFieldAccessors {
      get { return global::DotaMsgData.MsgData.internal__static_DotaMsgData_MSG_C2S_PUB_BEAT__FieldAccessorTable; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _mSGC2SPUBBEATFieldNames;
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static MSG_C2S_PUB_BEAT ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MSG_C2S_PUB_BEAT ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MSG_C2S_PUB_BEAT ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MSG_C2S_PUB_BEAT ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MSG_C2S_PUB_BEAT ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MSG_C2S_PUB_BEAT ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MSG_C2S_PUB_BEAT ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MSG_C2S_PUB_BEAT ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MSG_C2S_PUB_BEAT ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MSG_C2S_PUB_BEAT ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MSG_C2S_PUB_BEAT MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MSG_C2S_PUB_BEAT prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<MSG_C2S_PUB_BEAT, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MSG_C2S_PUB_BEAT cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MSG_C2S_PUB_BEAT result;
      
      private MSG_C2S_PUB_BEAT PrepareBuilder() {
        if (resultIsReadOnly) {
          MSG_C2S_PUB_BEAT original = result;
          result = new MSG_C2S_PUB_BEAT();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MSG_C2S_PUB_BEAT MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::DotaMsgData.MSG_C2S_PUB_BEAT.Descriptor; }
      }
      
      public override MSG_C2S_PUB_BEAT DefaultInstanceForType {
        get { return global::DotaMsgData.MSG_C2S_PUB_BEAT.DefaultInstance; }
      }
      
      public override MSG_C2S_PUB_BEAT BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is MSG_C2S_PUB_BEAT) {
          return MergeFrom((MSG_C2S_PUB_BEAT) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MSG_C2S_PUB_BEAT other) {
        if (other == global::DotaMsgData.MSG_C2S_PUB_BEAT.DefaultInstance) return this;
        PrepareBuilder();
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_mSGC2SPUBBEATFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _mSGC2SPUBBEATFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
    }
    static MSG_C2S_PUB_BEAT() {
      object.ReferenceEquals(global::DotaMsgData.MsgData.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class MSG_S2C_PUB_BEAT : pb::GeneratedMessage<MSG_S2C_PUB_BEAT, MSG_S2C_PUB_BEAT.Builder> {
    private MSG_S2C_PUB_BEAT() { }
    private static readonly MSG_S2C_PUB_BEAT defaultInstance = new MSG_S2C_PUB_BEAT().MakeReadOnly();
    private static readonly string[] _mSGS2CPUBBEATFieldNames = new string[] {  };
    private static readonly uint[] _mSGS2CPUBBEATFieldTags = new uint[] {  };
    public static MSG_S2C_PUB_BEAT DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MSG_S2C_PUB_BEAT DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MSG_S2C_PUB_BEAT ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::DotaMsgData.MsgData.internal__static_DotaMsgData_MSG_S2C_PUB_BEAT__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<MSG_S2C_PUB_BEAT, MSG_S2C_PUB_BEAT.Builder> InternalFieldAccessors {
      get { return global::DotaMsgData.MsgData.internal__static_DotaMsgData_MSG_S2C_PUB_BEAT__FieldAccessorTable; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _mSGS2CPUBBEATFieldNames;
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static MSG_S2C_PUB_BEAT ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MSG_S2C_PUB_BEAT ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MSG_S2C_PUB_BEAT ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MSG_S2C_PUB_BEAT ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MSG_S2C_PUB_BEAT ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MSG_S2C_PUB_BEAT ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MSG_S2C_PUB_BEAT ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MSG_S2C_PUB_BEAT ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MSG_S2C_PUB_BEAT ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MSG_S2C_PUB_BEAT ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MSG_S2C_PUB_BEAT MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MSG_S2C_PUB_BEAT prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<MSG_S2C_PUB_BEAT, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MSG_S2C_PUB_BEAT cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MSG_S2C_PUB_BEAT result;
      
      private MSG_S2C_PUB_BEAT PrepareBuilder() {
        if (resultIsReadOnly) {
          MSG_S2C_PUB_BEAT original = result;
          result = new MSG_S2C_PUB_BEAT();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MSG_S2C_PUB_BEAT MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::DotaMsgData.MSG_S2C_PUB_BEAT.Descriptor; }
      }
      
      public override MSG_S2C_PUB_BEAT DefaultInstanceForType {
        get { return global::DotaMsgData.MSG_S2C_PUB_BEAT.DefaultInstance; }
      }
      
      public override MSG_S2C_PUB_BEAT BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is MSG_S2C_PUB_BEAT) {
          return MergeFrom((MSG_S2C_PUB_BEAT) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MSG_S2C_PUB_BEAT other) {
        if (other == global::DotaMsgData.MSG_S2C_PUB_BEAT.DefaultInstance) return this;
        PrepareBuilder();
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_mSGS2CPUBBEATFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _mSGS2CPUBBEATFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
    }
    static MSG_S2C_PUB_BEAT() {
      object.ReferenceEquals(global::DotaMsgData.MsgData.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
