// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace DotaMsgID {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public static partial class MsgID {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static MsgID() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "CgtNc2dJRC5wcm90bxIJRG90YU1zZ0lEKm0KBU1TR0lEEhgKFENTSURfQzJM" + 
          "X0xPR0lOU0VSVkVSEGUSGAoUQ1NJRF9MMkNfTE9HSU5TRVJWRVIQZhIXChFD" + 
          "U0lEX0MyU19QVUJfQkVBVBCU6wESFwoRQ1NJRF9TMkNfUFVCX0JFQVQQlesB");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public enum MSGID {
    CSID_C2L_LOGINSERVER = 101,
    CSID_L2C_LOGINSERVER = 102,
    CSID_C2S_PUB_BEAT = 30100,
    CSID_S2C_PUB_BEAT = 30101,
  }
  
  #endregion
  
}

#endregion Designer generated code
